wn_blog_index:
    pattern: /index
    defaults: { _controller: WnBlogBundle:Blog:index }

wn_blog_index_element:
    pattern: /index/element
    defaults: { _controller: WnBlogBundle:Blog:element }

wn_blog_article_voir:
    pattern: /article/{id}
    defaults: { _controller: WnBlogBundle:Article:voir }
    requirements:
        id: \d+

wn_blog_test:
    pattern: /test
    defaults: { _controller: WnBlogBundle:Blog:test }

wn_blog_utilisateur:
    pattern: /profil/{id}
    defaults: { _controller: WnBlogBundle:Blog:profil }