wn_blog_homepage:
    pattern: /homepage
    defaults: { _controller: WnBlogBundle:Blog:homepage }

wn_blog_homepage_element_update:
    pattern: /homepage/element
    defaults: { _controller: WnBlogBundle:Blog:updateHomepageElement }

wn_blog_article_view:
    pattern: /article/{id}
    defaults: { _controller: WnBlogBundle:Article:view }
    requirements:
        id: \d+

wn_blog_user:
    pattern: /profile/{id}
    defaults: { _controller: WnBlogBundle:Blog:profile }

wn_blog_comment_view:
    pattern : /comment/{id}
    defaults: { _controller: WnBlogBundle:Comment:viewOnElement }