<?php

namespace Wn\GalleryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GalleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalleryRepository extends EntityRepository
{
	public function findByName($name){
		$query_builder = $this->createQueryBuilder('g')
							  ->where('g.name = :name')
							   ->setParameter('name',$name);

		return $query_builder->getQuery()
		                     ->getSingleResult();
	}
}
