<?php

namespace Wn\GalleryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ImageGalleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageGalleryRepository extends EntityRepository
{
	public function findLastNStartAtX($valueMax, $valueStart){
		$qb = $this->_em->createQueryBuilder();
		$qb->select('e')
		   ->from('WnGalleryBundle:ElementGallery','e')
		   ->orderBy('e.datePublication','DESC')
		   ->setFirstResult($valueStart)
		   ->setMaxResults($valueMax);

		return $qb->getQuery()
		          ->getResult();
	}

	public function findForUpdateHomepage($max_result, $list_id){
		$qb = $this->_em->createQueryBuilder();
		$qb->select('i')
		   ->from('WnGalleryBundle:ImageGallery','i')
		   ->where('i.id NOT IN (:ids)')
		    ->setParameter('ids',$list_id)
		   ->orderBy('i.dateOfPublication','DESC')
		   ->setMaxResults($max_result);

		return $qb->getQuery()
		          ->getResult();
	}
}
