<?php

namespace Wn\GalleryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ImageGalleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageGalleryRepository extends EntityRepository
{
	/**
	 * Used for adding new image in the homepage
	 * 
	 * @param integer        $max_result Number of image required
	 * @param array<integer> $list_id    List of id image already display on the homepage
 	 */
	public function findForUpdateHomepage($max_result, $list_id){
		$qb = $this->_em->createQueryBuilder();
		$qb->select('i')
		   ->from('WnGalleryBundle:ImageGallery','i')
		   ->where('i.id NOT IN (:ids)')
		    ->setParameter('ids',$list_id)
		   ->orderBy('i.dateOfPublication','DESC')
		   ->setMaxResults($max_result);

		return $qb->getQuery()
		          ->getResult();
	}
}
