<?php

namespace Wn\Model3DBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Model3DRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Model3DRepository extends EntityRepository
{
	/**
	 * Used for adding model 3D in the homepage
	 *
	 * @param  integer        $max_result Number of model required
	 * @param  array<integer> $list_id    List of id model already display in the homepage
	 * @return result
	 */
	public function findForUpdateHomepage($max_result, $list_id){
		$qb = $this->_em->createQueryBuilder();
		$qb->select('m')
		   ->from('WnModel3DBundle:Model3D','m')
		   ->where('m.id NOT IN (:ids)')
		    ->setParameter('ids',$list_id)
		   ->orderBy('m.dateOfPublication','DESC')
		   ->setMaxResults($max_result);

		return $qb->getQuery()
		          ->getResult();
	}
}
