<?php

namespace Wn\Model3DBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Model3DRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Model3DRepository extends EntityRepository
{
	public function findLastNStartAtX($valueMax, $valueStart){
		$qb = $this->_em->createQueryBuilder();
		$qb->select('m')
		   ->from('WnModel3DBundle:Model3D','m')
		   ->orderBy('m.datePublication','DESC')
		   ->setFirstResult($valueStart)
		   ->setMaxResults($valueMax);

		return $qb->getQuery()
		          ->getResult();
	}
}
