<?php

namespace Wn\Model3DBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TextureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TextureRepository extends EntityRepository
{
}
