<?php

namespace Wn\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends EntityRepository
{
	public function myFindByName($name){
		$qb = $this->_em->createQueryBuilder();

		$qb->select('c')
		   ->from('WnBlogBundle:Categorie','c')
		   ->where('c.nom = :name')
		    ->setParameter('name', $name);

		return $qb->getQuery()
		          ->getResult();
	}
}
