wn_backend_index:
    pattern: /index
    defaults: { _controller: WnBackendBundle:Backend:index }

wn_backend_login:
    pattern: /login
    defaults: { _controller: WnBackendBundle:Backend:login }

wn_backend_article:
    pattern: /article
    defaults: { _controller: WnBackendBundle:Backend:article }

wn_backend_article_add:
    pattern: /article/add
    defaults: { _controller: WnBlogBundle:Article:add }

wn_backend_article_edit:
    pattern: /article/edit/{id}
    defaults: { _controller: WnBlogBundle:Article:edit }
    requirements:
        id: \d+

wn_backend_article_delete:
    pattern: /article/delete/{id}
    defaults: { _controller: WnBlogBundle:Article:delete }
    requirements:
        id: \d+

wn_backend_comment:
    pattern: /comment
    defaults: { _controller: WnBackendBundle:Backend:comment }

wn_backend_comment_censor:
    pattern: /comment/censor/{id}
    defaults: { _controller: WnBlogBundle:Comment:censor }
    requirements:
        id: \d+

wn_backend_comment_uncensor:
    pattern: /comment/uncensor/{id}
    defaults: { _controller: WnBlogBundle:Comment:uncensor }
    requirements:
        id: \d+

wn_backend_comment_delete:
    pattern: /comment/delete/{id}
    defaults: { _controller: WnBlogBundle:Comment:delete }
    requirements:
        id: \d+

wn_backend_gallery:
    pattern: /gallery
    defaults: { _controller: WnBackendBundle:Backend:gallery }

wn_backend_gallery_add_image:
    pattern: /gallery/add
    defaults: { _controller: WnGalleryBundle:ImageGallery:add }

wn_backend_gallery_edit_image:
    pattern: /gallery/edit/{id}
    defaults: { _controller: WnGalleryBundle:ImageGallery:edit }
    requirements:
        id: \d+

wn_backend_gallery_delete_image:
    pattern: /gallery/delete/{id}
    defaults: { _controller: WnGalleryBundle:ImageGallery:delete }
    requirements:
        id: \d+

wn_backend_user:
    pattern: /user
    defaults: { _controller: WnBackendBundle:Backend:user }

wn_backend_category:
    pattern: /category
    defaults: { _controller: WnBackendBundle:Backend:category }

wn_backend_category_add:
    pattern: /category/add
    defaults: { _controller: WnBlogBundle:Category:add }

wn_backend_category_delete:
    pattern: /category/delete/{id}
    defaults: { _controller: WnBlogBundle:Category:delete }
    requirements:
        id: \d+

wn_backend_category_edit:
    pattern: /category/edit/{id}
    defaults: { _controller: WnBlogBundle:Category:edit }
    requirements:
        id: \d+

wn_backend_model:
    pattern: /model
    defaults: { _controller: WnBackendBundle:Backend:model3D }

wn_backend_model_add:
    pattern: /model/add
    defaults: { _controller: WnModel3DBundle:Model3D:add }

wn_backend_model_delete:
    pattern: /model/delete/{id}
    defaults: { _controller: WnModel3DBundle:Model3D:delete }
    requirements:
        id: \d+

wn_backend_model_edit:
    pattern: /model/edit/{id}
    defaults: { _controller: WnModel3DBundle:Model3D:edit }
    requirements:
        id: \d+

wn_backend_model_config:
    pattern: /model/config/{id}
    defaults: { _controller: WnModel3DBundle:Model3D:config }
    requirements:
        id: \d+