parameters:
#    wn_galerie.example.class: Wn\GalerieBundle\Example

services:
#    wn_galerie.example:
#        class: %wn_galerie.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
