<?php

namespace Wn\GalerieBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ElementGalerieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElementGalerieRepository extends EntityRepository
{
	public function findLastNStartAtX($valueMax, $valueStart){
		$qb = $this->_em->createQueryBuilder();
		$qb->select('e')
		   ->from('WnGalerieBundle:ElementGalerie','e')
		   ->orderBy('e.datePublication','DESC')
		   ->setFirstResult($valueStart)
		   ->setMaxResults($valueMax);

		return $qb->getQuery()
		          ->getResult();
	}
}
