<?php

namespace Wn\GalerieBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GalerieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalerieRepository extends EntityRepository
{
	public function findByNom($nom){
		$query_builder = $this->createQueryBuilder('g')
							  ->where('g.nom = :nom')
							   ->setParameter('nom',$nom);

		return $query_builder->getQuery()
		                     ->getSingleResult();
	}
}
