parameters:
#    wn_model3_d.example.class: Wn\Model3DBundle\Example

services:
#    wn_model3_d.example:
#        class: %wn_model3_d.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
